# Generated by Django 4.0 on 2025-04-18 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_deleted_at_ticket_deleted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='deleted_by',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='is_deleted',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('open', 'Abierto'), ('in_progress', 'En progreso'), ('closed', 'Cerrado')], default='open', max_length=20, verbose_name='Estado'),
        ),
    ]
